/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gfsk_receiver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(42998aff9af5d1fdc6151f392b9c098c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/robomaster/gfsk_receiver.h>
// pydoc.h is automatically generated in the build directory
#include <gfsk_receiver_pydoc.h>

void bind_gfsk_receiver(py::module& m)
{

    using gfsk_receiver    = gr::robomaster::gfsk_receiver;


    py::class_<gfsk_receiver, gr::block, gr::basic_block,
        std::shared_ptr<gfsk_receiver>>(m, "gfsk_receiver", D(gfsk_receiver))

        .def(py::init(&gfsk_receiver::make),
           D(gfsk_receiver,make)
        )
        



        ;




}








