/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gfsk_receiver_noise.h)                                     */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/robomaster/gfsk_receiver_noise.h>
#include <gfsk_receiver_noise_pydoc.h>

void bind_gfsk_receiver_noise(py::module& m)
{

    using gfsk_receiver_noise = gr::robomaster::gfsk_receiver_noise;

    py::class_<gfsk_receiver_noise, gr::block, gr::basic_block,
        std::shared_ptr<gfsk_receiver_noise>>(m, "gfsk_receiver_noise", D(gfsk_receiver_noise))

        .def(py::init(&gfsk_receiver_noise::make),
           D(gfsk_receiver_noise,make)
        )

        ;
}
